name: Publish NPM Package

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@platacard'

      - name: Install Dependencies
        run: npm ci

      - name: Publish packages
        run: npx nx release publish --projects=cli --registry=https://npm.pkg.github.com
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
