name: Release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - uses: nrwl/nx-set-shas@v4

      - run: npx nx build cli
      - run: npx nx build client
      - run: git config --global user.email "igor@katsuba.dev"
      - run: git config --global user.name "IKatsuba"
      - run: npx nx release --skip-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
